version: '3'

services:

  # TODO
  jupyter-lab:
    image: odapi
    volumes:
    - .:/home/oceanus
    ports:
    - "9000:9000"
    command:
    - "jupyter-lab --no-browser --ip=* --port=9000 --allow-root"

  tty:
    image: odapi
    volumes:
    - .:/home/oceanus
    stdin_open: true
    tty: true

  tensorflowjs-converter:
    image: odapi
    volumes:
    - .:/home/oceanus
    command:
    - "tensorflowjs_wizard"
