version: '3'

services:

  tty:
    build:
      context: ./dockerfiles
      dockerfile: odapi
      image: odapi
    volumes:
    - .:/home/oceanus
    stdin_open: true
    tty: true


  jupyter-lab:
    build:
      context: ./dockerfiles
      dockerfile: odapi.dockerfile
      image: odapi
    volumes:
    - .:/home/oceanus
    ports:
    - "9000:9000"
    command:
    - "jupyter-lab --no-browser --ip=* --port=9000 --allow-root"


  tensorflowjs-wizard:
    build:
      context: ./dockerfiles
      dockerfile: tfjs.dockerfile
      image: tfjs
    volumes:
    - .:/home/oceanus
    command:
    - "tensorflowjs_wizard"
